# utils/constants.py
# Global constants for the application

# Sections and subcategories for tutorials
SECTIONS = {
    "wallet": ["desktop", "hardware", "mobile", "backup"],
    "node": ["bitcoin", "lightning-network", "others"],
    "mining": ["hardware", "pool"],
    "exchange": ["centralized", "peer-to-peer"],
    "business": ["point-of-sale", "others"],
    "privacy": ["on-chain", "analysis"],
    "computer-security": ["authentication", "communication", "data", "operating system"],
    "contribution": ["content", "resource", "others"]
}

# Difficulty levels
LEVELS = ["beginner", "intermediate", "advanced", "expert"]

# Project categories (for projects)
PROJECT_CATEGORIES = [
    "communities", "conference", "education", "exchange", "infrastructure",
    "investment", "manufacturer", "merchant", "mining", "news",
    "node", "privacy", "service", "wallet"
]

# Language options for main languages
MAIN_LANGUAGE_CODES = {
    "en": "English",
    "es": "Español",
    "fr": "Français",
    "it": "Italiano"
}
MAIN_LANGUAGE_OPTIONS = [f"{code} ({MAIN_LANGUAGE_CODES[code]})" for code in MAIN_LANGUAGE_CODES]

# Other languages
OTHER_LANGUAGE_CODES = {
    "af": "Afrikaans",
    "am": "አማርኛ",
    "ar": "العربية",
    "as": "অসমীয়া",
    "az": "Azərbaycanca",
    "be": "Беларуская",
    "bg": "Български",
    "bn": "বাংলা",
    "bo": "བོད་སྐད་",
    "bs": "Bosanski",
    "ca": "Català",
    "ceb": "Cebuano",
    "co": "Corsu",
    "cs": "Čeština",
    "cy": "Cymraeg",
    "da": "Dansk",
    "de": "Deutsch",
    "dv": "ދިވެހިބަސް",
    "dz": "རྫོང་ཁ",
    "ee": "Eʋegbe",
    "el": "Ελληνικά",
    "eo": "Esperanto",
    "et": "Eesti",
    "eu": "Euskara",
    "fa": "فارسی",
    "fi": "Suomi",
    "fil": "Filipino",
    "fj": "Na Vosa Vakaviti",
    "fo": "Føroyskt",
    "fy": "Frysk",
    "ga": "Gaeilge",
    "gd": "Gàidhlig",
    "gl": "Galego",
    "gn": "Avañe'ẽ",
    "gu": "ગુજરાતી",
    "ha": "Hausa",
    "he": "עברית",
    "hi": "हिन्दी",
    "hmn": "Hmoob",
    "hr": "Hrvatski",
    "ht": "Kreyòl Ayisyen",
    "hu": "Magyar",
    "hy": "Հայերեն",
    "id": "Bahasa Indonesia",
    "ig": "Igbo",
    "is": "Íslenska",
    "ja": "日本語",
    "jv": "Basa Jawa",
    "ka": "ქართული",
    "kk": "Қазақша",
    "kl": "Kalaallisut",
    "km": "ខ្មែរ",
    "kn": "ಕನ್ನಡ",
    "ko": "한국어",
    "ku": "Kurdî",
    "ky": "Кыргызча",
    "la": "Latina",
    "lb": "Lëtzebuergesch",
    "lo": "ລາວ",
    "lt": "Lietuvių",
    "lv": "Latviešu",
    "mg": "Malagasy",
    "mi": "Māori",
    "mk": "Македонски",
    "ml": "മലയാളം",
    "mn": "Монгол",
    "mr": "मराठी",
    "ms": "Bahasa Melayu",
    "mt": "Malti",
    "my": "မြန်မာစာ",
    "nb": "Norsk Bokmål",
    "ne": "नेपाली",
    "nl": "Nederlands",
    "nn": "Norsk Nynorsk",
    "no": "Norsk",
    "ny": "Chichewa",
    "oc": "Occitan",
    "om": "Afaan Oromoo",
    "or": "ଓଡ଼ିଆ",
    "pa": "ਪੰਜਾਬੀ",
    "pl": "Polski",
    "ps": "پښتو",
    "pt": "Português",
    "ro": "Română",
    "ru": "Русский",
    "rw": "Kinyarwanda",
    "sd": "سنڌي",
    "si": "සිංහල",
    "sk": "Slovenčina",
    "sl": "Slovenščina",
    "sm": "Gagana Samoa",
    "sn": "ChiShona",
    "so": "Soomaali",
    "sq": "Shqip",
    "sr": "Српски",
    "ss": "SiSwati",
    "st": "Sesotho",
    "su": "Basa Sunda",
    "sv": "Svenska",
    "sw": "Kiswahili",
    "ta": "தமிழ்",
    "te": "తెలుగు",
    "tg": "Тоҷикӣ",
    "th": "ไทย",
    "ti": "ትግርኛ",
    "tk": "Türkmençe",
    "tl": "Tagalog",
    "tn": "Setswana",
    "tr": "Türkçe",
    "ts": "Xitsonga",
    "uk": "Українська",
    "ur": "اردو",
    "uz": "Oʻzbekcha",
    "vi": "Tiếng Việt",
    "xh": "isiXhosa",
    "yi": "ייִדיש",
    "yo": "Yorùbá",
    "zh": "中文",
    "zh-Hans": "简体中文",
    "zh-Hant": "繁體中文",
    "zu": "isiZulu"
}
SORTED_OTHER_LANGUAGES = sorted(OTHER_LANGUAGE_CODES)
OTHER_LANGUAGE_OPTIONS = [f"{code} ({OTHER_LANGUAGE_CODES[code]})" for code in SORTED_OTHER_LANGUAGES]
