# utils/constants.py
# Global constants for the application

# Sections and subcategories for tutorials
SECTIONS = {
    "wallet": ["desktop", "hardware", "mobile", "backup"],
    "node": ["bitcoin", "lightning-network", "others"],
    "mining": ["hardware", "pool"],
    "exchange": ["centralized", "peer-to-peer"],
    "business": ["point-of-sale", "others"],
    "privacy": ["on-chain", "explorer"],
    "computer-security": ["authentication", "communication", "data", "operating system"],
    "contribution": ["content", "resource", "others"]
}

# Difficulty levels
LEVELS = ["beginner", "intermediate", "advanced", "expert"]

# Project categories (for projects)
PROJECT_CATEGORIES = [
    "communities", "conference", "education", "exchange", "infrastructure",
    "investment", "manufacturer", "merchant", "mining", "news",
    "node", "privacy", "service", "wallet"
]

# License options
LICENSE_OPTIONS = ["CC-BY-SA-V4", "MIT"]
DEFAULT_LICENSE = LICENSE_OPTIONS[0]

# Language options for main languages
MAIN_LANGUAGE_CODES = {
    "en": "English",
    "es": "Español",
    "fr": "Français",
    "de": "Deutsch",
    "it": "Italiano"
}
MAIN_LANGUAGE_OPTIONS = [f"{code} ({MAIN_LANGUAGE_CODES[code]})" for code in MAIN_LANGUAGE_CODES]

# Other languages
OTHER_LANGUAGE_CODES = {
    "af": "Afrikaans",
    "am": "አማርኛ",
    "ar": "العربية",
    "ar-EG": "العربية (مصر)",
    "ar-SA": "العربية (السعودية)",
    "as": "অসমীয়া",
    "az": "Azərbaycanca",
    "be": "Беларуская",
    "bg": "Български",
    "bn": "বাংলা",
    "bn-BD": "বাংলা (বাংলাদেশ)",
    "bn-IN": "বাংলা (ভারত)",
    "bo": "བོད་སྐད་",
    "bs": "Bosanski",
    "ca": "Català",
    "ceb": "Cebuano",
    "co": "Corsu",
    "cs": "Čeština",
    "cs-CZ": "Čeština (Česko)",
    "cy": "Cymraeg",
    "da": "Dansk",
    "de": "Deutsch",
    "de-DE": "Deutsch (Deutschland)",
    "dv": "ދިވެހި",
    "dz": "རྫོང་ཁ",
    "ee": "Eʋegbe",
    "el": "Ελληνικά",
    "el-GR": "Ελληνικά (Ελλάδα)",
    "eo": "Esperanto",
    "et": "Eesti",
    "et-EE": "Eesti (Eesti)",
    "eu": "Euskara",
    "fa": "فارسی",
    "fa-IR": "فارسی (ایران)",
    "fi": "Suomi",
    "fi-FI": "Suomi (Suomi)",
    "fil": "Filipino",
    "fj": "Na Vosa Vakaviti",
    "fo": "Føroyskt",
    "fr-CA": "Français (Canada)",
    "fr-FR": "Français (France)",
    "fy": "Frysk",
    "ga": "Gaeilge",
    "gd": "Gàidhlig",
    "gl": "Galego",
    "gn": "Avañe'ẽ",
    "gu": "ગુજરાતી",
    "ha": "Hausa",
    "he": "עברית",
    "he-IL": "עברית (ישראל)",
    "hi": "हिन्दी",
    "hi-IN": "हिन्दी (भारत)",
    "hmn": "Hmoob",
    "hr": "Hrvatski",
    "ht": "Kreyòl Ayisyen",
    "hu": "Magyar",
    "hy": "Հայերեն",
    "id": "Bahasa Indonesia",
    "id-ID": "Bahasa Indonesia (Indonesia)",
    "ig": "Igbo",
    "is": "Íslenska",
    "it-IT": "Italiano (Italia)",
    "ja": "日本語",
    "ja-JP": "日本語 (日本)",
    "jv": "Basa Jawa",
    "ka": "ქართული",
    "kk": "Қазақша",
    "kl": "Kalaallisut",
    "km": "ខ្មែរ",
    "kn": "ಕನ್ನಡ",
    "ko": "한국어",
    "ko-KR": "한국어 (대한민국)",
    "ku": "Kurdî",
    "ky": "Кыргызча",
    "la": "Latina",
    "lb": "Lëtzebuergesch",
    "lo": "ລາວ",
    "lt": "Lietuvių",
    "lv": "Latviešu",
    "mg": "Malagasy",
    "mi": "Māori",
    "mk": "Македонски",
    "ml": "മലയാളം",
    "mn": "Монгол",
    "mr": "मराठी",
    "ms": "Bahasa Melayu",
    "ms-MY": "Bahasa Melayu (Malaysia)",
    "mt": "Malti",
    "my": "မြန်မာစာ",
    "nb": "Norsk Bokmål",
    "nb-NO": "Norsk Bokmål (Norge)",
    "ne": "नेपाली",
    "nl": "Nederlands",
    "nl-NL": "Nederlands (Nederland)",
    "nn": "Norsk Nynorsk",
    "nn-NO": "Norsk Nynorsk (Noreg)",
    "no": "Norsk",
    "no-NO": "Norsk (Norge)",
    "ny": "Chichewa",
    "oc": "Occitan",
    "om": "Afaan Oromoo",
    "or": "ଓଡ଼ିଆ",
    "pa": "ਪੰਜਾਬੀ",
    "pl": "Polski",
    "pl-PL": "Polski (Polska)",
    "ps": "پښتو",
    "pt": "Português",
    "pt-BR": "Português (Brasil)",
    "pt-PT": "Português (Portugal)",
    "ro": "Română",
    "ru": "Русский",
    "ru-RU": "Русский (Россия)",
    "rw": "Kinyarwanda",
    "sd": "سنڌي",
    "si": "සිංහල",
    "sk": "Slovenčina",
    "sl": "Slovenščina",
    "sm": "Gagana Samoa",
    "sn": "ChiShona",
    "so": "Soomaali",
    "sq": "Shqip",
    "sr": "Српски",
    "sr-Cyrl": "Српски (Ћирилица)",
    "sr-Latn": "Srpski (Latinica)",
    "ss": "SiSwati",
    "st": "Sesotho",
    "su": "Basa Sunda",
    "sv": "Svenska",
    "sv-SE": "Svenska (Sverige)",
    "sw": "Kiswahili",
    "sw-KE": "Kiswahili (Kenya)",
    "sw-TZ": "Kiswahili (Tanzania)",
    "ta": "தமிழ்",
    "ta-IN": "தமிழ் (இந்தியா)",
    "ta-LK": "தமிழ் (இலங்கை)",
    "te": "తెలుగు",
    "tg": "Тоҷикӣ",
    "th": "ไทย",
    "ti": "ትግርኛ",
    "tk": "Türkmençe",
    "tl": "Tagalog",
    "tn": "Setswana",
    "tr": "Türkçe",
    "tr-TR": "Türkçe (Türkiye)",
    "ts": "Xitsonga",
    "uk": "Українська",
    "uk-UA": "Українська (Україна)",
    "ur": "اردو",
    "uz": "Oʻzbekcha",
    "vi": "Tiếng Việt",
    "vi-VN": "Tiếng Việt (Việt Nam)",
    "xh": "isiXhosa",
    "yi": "ייִדיש",
    "yo": "Yorùbá",
    "zh": "中文",
    "zh-CN": "简体中文（中国）",
    "zh-HK": "繁體中文（香港）",
    "zh-Hans": "简体中文",
    "zh-Hant": "繁體中文",
    "zh-SG": "简体中文（新加坡）",
    "zh-TW": "繁體中文（台灣）",
    "zu": "isiZulu"
}

SORTED_OTHER_LANGUAGES = sorted(OTHER_LANGUAGE_CODES)
OTHER_LANGUAGE_OPTIONS = [f"{code} ({OTHER_LANGUAGE_CODES[code]})" for code in SORTED_OTHER_LANGUAGES]
